/**
 * Tests for gemma-session-notes edge function logic.
 *
 * Run with:
 *   ~/.deno/bin/deno test --allow-env supabase/functions/gemma-session-notes/index.test.ts
 */

import { assertEquals, assertMatch, assertExists } from 'https://deno.land/std@0.224.0/assert/mod.ts';

// ---------------------------------------------------------------------------
// Pure logic mirrored from index.ts
// ---------------------------------------------------------------------------

interface SessionNote {
  presenting_issue: string;
  session_focus: string;
  key_observations: string[];
  follow_up_actions: string[];
  mood_rating?: string;
}

function buildNoteMarkdown(note: SessionNote): string {
  return [
    `## Presenting Issue\n${note.presenting_issue}`,
    `## Session Focus\n${note.session_focus}`,
    `## Key Observations\n${note.key_observations.map((o) => `- ${o}`).join('\n')}`,
    `## Follow-Up Actions\n${note.follow_up_actions.map((a) => `- ${a}`).join('\n')}`,
    note.mood_rating ? `## Client Mood (End of Session)\n${note.mood_rating}` : '',
    `\n---\n*Generated by Gemma 4 — Nawe AI*`,
  ].filter(Boolean).join('\n\n');
}

function extractGoogleAINoteResult(response: Record<string, unknown>): SessionNote | null {
  const parts = (
    ((response.candidates as Record<string, unknown>[])?.[0]?.content as Record<string, unknown>)?.parts as Record<string, unknown>[]
  ) ?? [];
  const fnPart = parts.find((p) => p.functionCall);
  if (!fnPart) return null;
  const fc = fnPart.functionCall as Record<string, unknown>;
  return fc.args as SessionNote;
}

function extractOllamaNoteResult(response: Record<string, unknown>): SessionNote | null {
  const toolCall = (response.message as Record<string, unknown>)?.tool_calls as { function: { name: string; arguments: SessionNote } }[] | undefined;
  const call = toolCall?.[0];
  if (call?.function?.name === 'submit_session_note') return call.function.arguments;
  return null;
}

function buildContextPrompt(session: {
  scheduled_at: string;
  session_format?: string;
  duration_minutes?: number;
  notes_client?: string | null;
}, triage?: { presenting_issue?: string; urgency?: string; summary?: string } | null): string {
  const sessionDate = new Intl.DateTimeFormat('en-GB', {
    dateStyle: 'full', timeStyle: 'short', timeZone: 'Africa/Nairobi',
  }).format(new Date(session.scheduled_at));

  return [
    `Session date: ${sessionDate}`,
    `Format: ${session.session_format ?? 'unspecified'}`,
    `Duration: ${session.duration_minutes ?? 50} minutes`,
    session.notes_client ? `Client notes before session: "${session.notes_client}"` : null,
    triage?.presenting_issue ? `Intake presenting issue: "${triage.presenting_issue}"` : null,
    triage?.urgency ? `Intake urgency level: ${triage.urgency}` : null,
    triage?.summary ? `Intake summary: "${triage.summary}"` : null,
  ].filter(Boolean).join('\n');
}

// ---------------------------------------------------------------------------
// Markdown builder
// ---------------------------------------------------------------------------

Deno.test('buildNoteMarkdown: includes all required sections', () => {
  const note: SessionNote = {
    presenting_issue: 'Anxiety and workplace stress',
    session_focus: 'Cognitive reframing techniques',
    key_observations: ['Client showed awareness of triggers', 'Avoidance patterns identified'],
    follow_up_actions: ['Practice breathing exercises', 'Journal daily triggers'],
    mood_rating: 'improved',
  };

  const md = buildNoteMarkdown(note);
  assertMatch(md, /## Presenting Issue/);
  assertMatch(md, /## Session Focus/);
  assertMatch(md, /## Key Observations/);
  assertMatch(md, /## Follow-Up Actions/);
  assertMatch(md, /## Client Mood/);
  assertMatch(md, /Generated by Gemma 4/);
});

Deno.test('buildNoteMarkdown: key_observations rendered as bullet list', () => {
  const note: SessionNote = {
    presenting_issue: 'Depression',
    session_focus: 'Behavioural activation',
    key_observations: ['Low energy reported', 'Sleep disruption noted'],
    follow_up_actions: ['Daily walk goal'],
  };

  const md = buildNoteMarkdown(note);
  assertMatch(md, /- Low energy reported/);
  assertMatch(md, /- Sleep disruption noted/);
});

Deno.test('buildNoteMarkdown: omits mood section when not provided', () => {
  const note: SessionNote = {
    presenting_issue: 'Stress',
    session_focus: 'Stress management',
    key_observations: ['Client engaged well'],
    follow_up_actions: ['Mindfulness exercise'],
  };

  const md = buildNoteMarkdown(note);
  assertEquals(md.includes('## Client Mood'), false);
});

Deno.test('buildNoteMarkdown: follow_up_actions rendered as bullet list', () => {
  const note: SessionNote = {
    presenting_issue: 'Anxiety',
    session_focus: 'Exposure therapy intro',
    key_observations: ['Motivation present'],
    follow_up_actions: ['Rate anxiety daily', 'Try one avoided activity'],
  };

  const md = buildNoteMarkdown(note);
  assertMatch(md, /- Rate anxiety daily/);
  assertMatch(md, /- Try one avoided activity/);
});

// ---------------------------------------------------------------------------
// Google AI Studio response parsing
// ---------------------------------------------------------------------------

Deno.test('extractGoogleAINoteResult: extracts structured note from function call', () => {
  const mockResponse = {
    candidates: [{
      content: {
        parts: [{
          functionCall: {
            name: 'submit_session_note',
            args: {
              presenting_issue: 'Workplace anxiety',
              session_focus: 'CBT — identifying cognitive distortions',
              key_observations: ['Catastrophising identified', 'Good rapport established'],
              follow_up_actions: ['Thought diary', 'Review ABC model'],
              mood_rating: 'improved',
            },
          },
        }],
        role: 'model',
      },
    }],
  };

  const note = extractGoogleAINoteResult(mockResponse);
  assertExists(note);
  assertEquals(note!.presenting_issue, 'Workplace anxiety');
  assertEquals(note!.key_observations.length, 2);
  assertEquals(note!.mood_rating, 'improved');
});

Deno.test('extractGoogleAINoteResult: returns null when no function call', () => {
  const mockResponse = {
    candidates: [{
      content: {
        parts: [{ text: 'Here is the session note...' }],
        role: 'model',
      },
    }],
  };

  const note = extractGoogleAINoteResult(mockResponse);
  assertEquals(note, null);
});

// ---------------------------------------------------------------------------
// Ollama response parsing
// ---------------------------------------------------------------------------

Deno.test('extractOllamaNoteResult: extracts structured note from tool call', () => {
  const mockResponse = {
    message: {
      role: 'assistant',
      content: '',
      tool_calls: [{
        function: {
          name: 'submit_session_note',
          arguments: {
            presenting_issue: 'Grief after bereavement',
            session_focus: 'Normalising grief responses',
            key_observations: ['Tearful but engaged', 'Support network limited'],
            follow_up_actions: ['Contact one friend this week'],
            mood_rating: 'neutral',
          },
        },
      }],
    },
  };

  const note = extractOllamaNoteResult(mockResponse);
  assertExists(note);
  assertEquals(note!.presenting_issue, 'Grief after bereavement');
  assertEquals(note!.mood_rating, 'neutral');
});

Deno.test('extractOllamaNoteResult: returns null when no tool call', () => {
  const mockResponse = {
    message: { role: 'assistant', content: 'Here is a note...' },
  };

  assertEquals(extractOllamaNoteResult(mockResponse), null);
});

// ---------------------------------------------------------------------------
// Context prompt builder
// ---------------------------------------------------------------------------

Deno.test('buildContextPrompt: includes session format and duration', () => {
  const prompt = buildContextPrompt({
    scheduled_at: '2026-05-17T10:00:00Z',
    session_format: 'Video',
    duration_minutes: 60,
  });

  assertMatch(prompt, /Format: Video/);
  assertMatch(prompt, /Duration: 60 minutes/);
});

Deno.test('buildContextPrompt: includes client notes when present', () => {
  const prompt = buildContextPrompt({
    scheduled_at: '2026-05-17T10:00:00Z',
    notes_client: 'Feeling overwhelmed at work this week',
  });

  assertMatch(prompt, /Feeling overwhelmed at work this week/);
});

Deno.test('buildContextPrompt: omits client notes section when null', () => {
  const prompt = buildContextPrompt({
    scheduled_at: '2026-05-17T10:00:00Z',
    notes_client: null,
  });

  assertEquals(prompt.includes('Client notes before session'), false);
});

Deno.test('buildContextPrompt: includes triage data when available', () => {
  const prompt = buildContextPrompt(
    { scheduled_at: '2026-05-17T10:00:00Z' },
    { presenting_issue: 'anxiety', urgency: 'moderate', summary: 'Work-related stress' },
  );

  assertMatch(prompt, /Intake presenting issue: "anxiety"/);
  assertMatch(prompt, /Intake urgency level: moderate/);
  assertMatch(prompt, /Intake summary: "Work-related stress"/);
});

Deno.test('buildContextPrompt: omits triage section when not available', () => {
  const prompt = buildContextPrompt({ scheduled_at: '2026-05-17T10:00:00Z' }, null);

  assertEquals(prompt.includes('Intake'), false);
});

Deno.test('buildContextPrompt: defaults duration to 50 minutes', () => {
  const prompt = buildContextPrompt({ scheduled_at: '2026-05-17T10:00:00Z' });
  assertMatch(prompt, /Duration: 50 minutes/);
});
