import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const googleApiKey = Deno.env.get('GOOGLE_AI_API_KEY') ?? '';
const googleModel = Deno.env.get('GEMMA_MODEL') ?? 'gemma-4-9b-it';
const ollamaBaseUrl = Deno.env.get('OLLAMA_BASE_URL') ?? 'http://localhost:11434';
const ollamaModel = Deno.env.get('OLLAMA_MODEL') ?? 'gemma4:4b';
const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? '';
const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY') ?? '';
const supabaseServiceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';

const SESSION_NOTES_TOOL = {
  type: 'function',
  function: {
    name: 'submit_session_note',
    description: 'Submit the structured session note.',
    parameters: {
      type: 'object',
      required: ['presenting_issue', 'session_focus', 'key_observations', 'follow_up_actions'],
      properties: {
        presenting_issue: {
          type: 'string',
          description: 'The main issue the client brought to this session',
        },
        session_focus: {
          type: 'string',
          description: 'What was the primary therapeutic focus of this session',
        },
        key_observations: {
          type: 'array',
          items: { type: 'string' },
          description: 'Up to 4 clinical observations from the session',
        },
        follow_up_actions: {
          type: 'array',
          items: { type: 'string' },
          description: 'Suggested actions or topics for the next session',
        },
        mood_rating: {
          type: 'string',
          description: 'Estimated client mood at end of session: "low", "neutral", "improved"',
        },
      },
    },
  },
};

interface SessionNote {
  presenting_issue: string;
  session_focus: string;
  key_observations: string[];
  follow_up_actions: string[];
  mood_rating?: string;
}

function buildNoteMarkdown(note: SessionNote): string {
  return [
    `## Presenting Issue\n${note.presenting_issue}`,
    `## Session Focus\n${note.session_focus}`,
    `## Key Observations\n${note.key_observations.map(o => `- ${o}`).join('\n')}`,
    `## Follow-Up Actions\n${note.follow_up_actions.map(a => `- ${a}`).join('\n')}`,
    note.mood_rating ? `## Client Mood (End of Session)\n${note.mood_rating}` : '',
    `\n---\n*Generated by Gemma 4 — Nawe AI*`,
  ].filter(Boolean).join('\n\n');
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders });
  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const authHeader = req.headers.get('Authorization') ?? '';
  if (!authHeader) {
    return new Response(JSON.stringify({ error: 'Missing authorization header' }), {
      status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // Verify therapist
  const authClient = createClient(supabaseUrl, supabaseAnonKey, {
    auth: { persistSession: false, autoRefreshToken: false },
    global: { headers: { Authorization: authHeader } },
  });
  const { data: userData, error: userError } = await authClient.auth.getUser();
  if (userError || !userData.user) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  let session_id: string;
  try {
    const body = await req.json();
    session_id = body.session_id;
    if (!session_id) throw new Error('session_id is required');
  } catch (e) {
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : 'Invalid body' }), {
      status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const adminClient = createClient(supabaseUrl, supabaseServiceRoleKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  try {
    // Fetch session details
    const { data: session, error: sessionError } = await adminClient
      .from('sessions')
      .select('id, client_id, therapist_id, scheduled_at, session_format, duration_minutes, notes_client, status')
      .eq('id', session_id)
      .maybeSingle();

    if (sessionError) throw sessionError;
    if (!session) {
      return new Response(JSON.stringify({ error: 'Session not found' }), {
        status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Verify caller owns this session as therapist
    const { data: therapist } = await adminClient
      .from('therapists')
      .select('id')
      .eq('user_id', userData.user.id)
      .maybeSingle();

    if (!therapist || therapist.id !== session.therapist_id) {
      return new Response(JSON.stringify({ error: 'Forbidden' }), {
        status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Fetch client triage summary if available
    const { data: triage } = await adminClient
      .from('triage_results')
      .select('presenting_issue, urgency, summary, therapist_type')
      .eq('user_id', session.client_id)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    // Build context prompt
    const sessionDate = new Intl.DateTimeFormat('en-GB', {
      dateStyle: 'full', timeStyle: 'short', timeZone: 'Africa/Nairobi',
    }).format(new Date(session.scheduled_at));

    const contextLines = [
      `Session date: ${sessionDate}`,
      `Format: ${session.session_format ?? 'unspecified'}`,
      `Duration: ${session.duration_minutes ?? 50} minutes`,
      session.notes_client ? `Client notes before session: "${session.notes_client}"` : null,
      triage?.presenting_issue ? `Intake presenting issue: "${triage.presenting_issue}"` : null,
      triage?.urgency ? `Intake urgency level: ${triage.urgency}` : null,
      triage?.summary ? `Intake summary: "${triage.summary}"` : null,
    ].filter(Boolean).join('\n');

    const prompt = `You are assisting a licensed therapist at Nawe, a mental health platform in East Africa. Generate a structured session note based on the session context below. Be clinical but concise. Call submit_session_note with your assessment.

Session context:
${contextLines}`;

    // Call Gemma 4 — Google AI Studio if key is set, else Ollama
    let toolCall: { function: { name: string; arguments: SessionNote } } | undefined;

    if (googleApiKey) {
      const body = {
        contents: [{ role: 'user', parts: [{ text: prompt }] }],
        tools: [{ function_declarations: [SESSION_NOTES_TOOL.function] }],
      };
      const googleResp = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${googleModel}:generateContent?key=${googleApiKey}`,
        { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) },
      );
      if (!googleResp.ok) throw new Error(`Google AI error (${googleResp.status}): ${await googleResp.text()}`);
      const googleData = await googleResp.json();
      const parts = googleData.candidates?.[0]?.content?.parts ?? [];
      const fnPart = parts.find((p: Record<string, unknown>) => p.functionCall);
      if (fnPart) toolCall = { function: { name: fnPart.functionCall.name, arguments: fnPart.functionCall.args } };
    } else {
      const ollamaResp = await fetch(`${ollamaBaseUrl}/api/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: ollamaModel,
          messages: [{ role: 'user', content: prompt }],
          tools: [SESSION_NOTES_TOOL],
          stream: false,
        }),
      });
      if (!ollamaResp.ok) throw new Error(`Ollama error: ${ollamaResp.status} ${await ollamaResp.text()}`);
      const ollamaData = await ollamaResp.json();
      toolCall = ollamaData.message?.tool_calls?.[0];
    }

    if (!toolCall || toolCall.function?.name !== 'submit_session_note') {
      // Fallback: use raw content if no tool call
      const rawContent = ollamaData.message?.content ?? 'Session note generation failed.';
      const { data: note } = await adminClient
        .from('session_notes')
        .upsert({ session_id, therapist_id: therapist.id, content: rawContent }, { onConflict: 'session_id' })
        .select('id, content')
        .single();
      return new Response(JSON.stringify({ note_id: note?.id, content: note?.content }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const noteData = toolCall.function.arguments as SessionNote;
    const markdown = buildNoteMarkdown(noteData);

    // Save or update the session note
    const { data: savedNote, error: noteError } = await adminClient
      .from('session_notes')
      .upsert({ session_id, therapist_id: therapist.id, content: markdown }, { onConflict: 'session_id' })
      .select('id, content')
      .single();

    if (noteError) throw noteError;

    return new Response(
      JSON.stringify({ note_id: savedNote.id, content: savedNote.content, structured: noteData }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
    );
  } catch (err) {
    console.error('gemma-session-notes error:', err);
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : 'Unexpected error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
    );
  }
});
